#ifndef TAG_H
#define TAG_H

enum Tag { 
  BEG = 256, END,
  COMMA, DOT, SEMI,
  LHRND, RHRND, LHSQR, RHSQR,
  WRITE, ASGN, IF, DO, ELIF, ENDIF, LOOP, ENDLOOP, SKIP,
  AND, OR, NOT,
  INIT, EQ, NEQ, LESS, GREATER, LEQ, GEQ,
  PLUS, MINUS, MULT, DIV, MOD,
  ARRAY, PROC, ENDPROC, RECORD, ENDREC, TYPE,
  INT, BOOL, FLOAT, CHAR, CONST,
  NUMBER, TRUE, FALSE, NAME, CHARACTER,
};

#endif;
